spring:
  application:
    name: redisson-cache-consistency
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://host.docker.internal:6379"
server:
  port: 8080
